var theLinks = {
    /* target 取值 self、_blank */
    target: 'self',
    /*
        {name:"",link:"",describe:""},
     
        {
            name:"",
            links:[
                {name:"",link:""},
                {name:"",link:""}
            ]
        },
    */
    links: {
        goodLinks:[
            {name:"菜鸟工具",link:"https://c.runoob.com/",describe:"多种工具"},
            {name:"TOOLFK",link:"https://www.toolfk.com/",describe:"各种工具"},
            {name:"资源狗",link:"http://www.ziyuangou.com/",describe:"写这个网页的灵感来源"},
        ],
        goldLinks:[{
            name:"搜索主页",
            links:[
				{name:"goobe",link:"https://goobe.io/"},
				{name:"Bing",link:"https://cn.bing.com/?FORM=BEHPTB"},
				{name:"百度",link:"https://baike.baidu.com/"},
            ]
        },{
            name:"生活社区",
            links:[
                {name:"哔哩哔哩",link:"https://www.bilibili.com/"},
                {name:"微博",link:"https://weibo.com/"},
                {name:"知乎",link:"https://www.zhihu.com/"},
                {name:"场库",link:"https://www.vmovier.com/"},
				{name:"找到 AI",link:"https://zhaodao.ai/"}
            ]
        },{
            name:"持续好好学习",
            links:[
                {name:"微信读书",link:"https://weread.qq.com/"},
                {name:"TED",link:"https://www.ted.com/#/"},
                {name:"慕课",link:"https://www.icourse163.org/"},
                {name:"网易公开课",link:"https://open.163.com/"}
            ]
        },{
            name:"技术交流社区",
            links:[
				{name:"segmentfault",link:"https://segmentfault.com/"},
				{name:"stackoverflow",link:"https://stackoverflow.com/"},
                {name:"GitHub",link:"https://github.com/"},
                {name:"npm 官网",link:"https://www.npmjs.com/"},
                {name:"力扣",link:"https://leetcode-cn.com/problemset/all/"},
                {name:"牛客网",link:"https://www.nowcoder.com/"},
                {name:"CSDN",link:"https://www.csdn.net"},
                {name:"菜鸟教程",link:"https://www.runoob.com/"},
                {name:"W3school",link:"https://www.w3school.com.cn/index.html"},
                {name:"w3cschool",link:"https://www.w3cschool.cn/"},
                {name:"how2j.cn",link:"https://how2j.cn/"}
            ]
        },{
            name:"技术学习",
            links:[
                {name:"alloyteam",link:"http://www.alloyteam.com/"},
                {name:"美团技术团队",link:"https://tech.meituan.com/"},
                {name:"优质的中文前端博客",link:"https://github.com/FrankFang/best-chinese-front-end-blogs"},
                {name:"大漠",link:"https://www.w3cplus.com/"},
                {name:"廖雪峰的官方网站",link:"https://www.liaoxuefeng.com/"},
                {name:"张鑫旭的个人主页",link:"https://www.zhangxinxu.com/"},
                {name:"柳婼 の blog",link:"https://www.liuchuo.net/"}
            ]
        },{
            name:"学学设计",
            links:[
				{name:"站酷",link:"https://www.zcool.com.cn/"},
				{name:"花瓣",link:"https://huaban.com/"}
            ]
        },{
            name:"偶尔打打游戏",
            links:[
                {name:"HTML5 games",link:"https://html5games.com/"},
                {name:"游侠网",link:"https://www.ali213.net/"},
                {name:"4399小游戏",link:"http://www.4399.com/"}
            ]
        },{
            name:"看电影",
            links:[
                {name:"80s手机电影网",link:"https://www.80s.tw/"},
                {name:"80S电影网",link:"http://80smp4.cc/"},
                {name:"电影天堂",link:"http://www.kk2w1.com/"},
                {name:"人人影视",link:"http://www.renren163.com/"}
            ]
        },{
            name:"看动漫",
            links:[
                {name:"奇奇动漫",link:"https://www.qiqidongman.com/"}
            ]
        },{
            name:"求职",
            links:[
                {name:"BOSS直聘",link:"https://www.zhipin.com/"},
                {name:"新职业",link:"https://www.ncss.cn/"}
            ]
        },{
            name:"网上接单",
            links:[
                {name:"猪八戒网",link:"https://nanchang.zbj.com/"},
                {name:"一品威客",link:"https://www.epwk.com/"},
                {name:"猿急送",link:"https://www.yuanjisong.com/"}
            ]
        },{
            name:"租房",
            links:[
                {name:"自如",link:"http://www.ziroom.com/"}
            ]
        },{
            name:"线上商城",
            links:[
                {name:"淘宝网",link:"https://www.taobao.com/"},
                {name:"天猫",link:"https://www.tmall.com/"},
                {name:"京东",link:"https://www.jd.com/"},
                {name:"亚马逊",link:"https://www.amazon.cn/s/ref=nb_sb_noss"}
            ]
        },{
            name:"在线翻译",
            links:[
                {name:"百度翻译",link:"https://fanyi.baidu.com/translate"}
            ]
        },{
            name:"地图",
            links:[
                {name:"百度地图",link:"https://map.baidu.com/"}
            ]
        },{
            name:"学术交流",
            links:[
                {name:"中国知网",link:"https://www.cnki.net/"},
                {name:"百度学术",link:"https://xueshu.baidu.com/"}
            ]
        }]
    }
}